services:
  - type: web
    name: crossword-backend
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: postgresql+asyncpg://postgres.juxqzsyioehjqztthyoy:crosswordxcellcell55@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?ssl=require
      - key: CORS_ORIGINS
        value: "*"
