services:
  - type: web
    name: crossword-backend
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: postgresql+asyncpg://neondb_owner:npg_Trk2AdZJxI1v@ep-long-haze-b57x6p7c-pooler.c-7.us-east-2.aws.neon.tech/neondb?ssl=require
      - key: CORS_ORIGINS
        value: "*"
