"""Offline definition database for standard English and Scrabble words."""

OFFLINE_DEFINITIONS: dict[str, dict] = {
    # 2-letter Scrabble words
    "AA": {"phonetic": "/ˈɑː.ɑː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A type of basaltic lava forming rough, jagged masses."]}]},
    "AB": {"phonetic": "/æb/", "meanings": [{"partOfSpeech": "noun", "definitions": ["An abdominal muscle."]}]},
    "AD": {"phonetic": "/æd/", "meanings": [{"partOfSpeech": "noun", "definitions": ["An advertisement."]}]},
    "AE": {"phonetic": "/iː/", "meanings": [{"partOfSpeech": "adjective", "definitions": ["One (Scottish)."]}]},
    "AG": {"phonetic": "/æɡ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["Agriculture."]}]},
    "AH": {"phonetic": "/ɑː/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Expressing pleasure, relief, surprise, or sympathy."]}]},
    "AI": {"phonetic": "/aɪ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A three-toed sloth; artificial intelligence."]}]},
    "AL": {"phonetic": "/æl/", "meanings": [{"partOfSpeech": "noun", "definitions": ["An East Indian tree (Morinda citrifolia)."]}]},
    "AM": {"phonetic": "/æm/", "meanings": [{"partOfSpeech": "verb", "definitions": ["First-person singular present indicative of be."]}]},
    "AN": {"phonetic": "/æn/", "meanings": [{"partOfSpeech": "article", "definitions": ["The form of the indefinite article used before words beginning with a vowel sound."]}]},
    "AR": {"phonetic": "/ɑːr/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The letter R."]}]},
    "AS": {"phonetic": "/æz/", "meanings": [{"partOfSpeech": "adverb", "definitions": ["Used in comparisons to refer to the extent or degree of something."]}]},
    "AT": {"phonetic": "/æt/", "meanings": [{"partOfSpeech": "preposition", "definitions": ["Expressing location or arrival in a particular place or position."]}]},
    "AW": {"phonetic": "/ɔː/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Expressing mild protest, sympathy, or disbelief."]}]},
    "AX": {"phonetic": "/æks/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A cutting tool that consists of a heavy edged head fixed to a handle."]}]},
    "AY": {"phonetic": "/aɪ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["An affirmative vote; aye."]}]},
    "BA": {"phonetic": "/bɑː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["In ancient Egyptian religion, the soul."]}]},
    "BE": {"phonetic": "/biː/", "meanings": [{"partOfSpeech": "verb", "definitions": ["Exist or occur; have a specified status or quality."]}]},
    "BI": {"phonetic": "/baɪ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A bisexual person."]}]},
    "BO": {"phonetic": "/boʊ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A fellow; buddy (slang)."]}]},
    "BY": {"phonetic": "/baɪ/", "meanings": [{"partOfSpeech": "preposition", "definitions": ["Identifying the agent performing an action; near to."]}]},
    "CH": {"phonetic": "/tʃ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["Dialect form of I (pronoun)."]}]},
    "DA": {"phonetic": "/dɑː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["Father or dad."]}]},
    "DE": {"phonetic": "/diː/", "meanings": [{"partOfSpeech": "preposition", "definitions": ["Of; from (used in names)."]}]},
    "DI": {"phonetic": "/daɪ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["Plural of deus (god)."]}]},
    "DO": {"phonetic": "/duː/", "meanings": [{"partOfSpeech": "verb", "definitions": ["Perform an action, the precise nature of which is often unspecified."]}]},
    "EA": {"phonetic": "/iːə/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A river or watercourse (dialect)."]}]},
    "ED": {"phonetic": "/ɛd/", "meanings": [{"partOfSpeech": "noun", "definitions": ["Education."]}]},
    "EE": {"phonetic": "/iː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["Eye (dialect)."]}]},
    "EF": {"phonetic": "/ɛf/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The letter F."]}]},
    "EH": {"phonetic": "/eɪ/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Used to represent a sound made in inquiry, surprise, or doubt."]}]},
    "EL": {"phonetic": "/ɛl/", "meanings": [{"partOfSpeech": "noun", "definitions": ["An elevated railroad or train."]}]},
    "EM": {"phonetic": "/ɛm/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A unit of measurement in typography equal to the current point size."]}]},
    "EN": {"phonetic": "/ɛn/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A unit of measurement in typography equal to half an em."]}]},
    "ER": {"phonetic": "/ɜːr/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Used to express hesitation or pause in speech."]}]},
    "ES": {"phonetic": "/ɛs/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The letter S."]}]},
    "ET": {"phonetic": "/ɛt/", "meanings": [{"partOfSpeech": "verb", "definitions": ["Archaic or dialect past tense and past participle of eat."]}]},
    "EW": {"phonetic": "/juː/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Used to express disgust or distaste."]}]},
    "EX": {"phonetic": "/ɛks/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A former spouse or partner."]}]},
    "FA": {"phonetic": "/fɑː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The fourth tone of the diatonic scale in solfège."]}]},
    "FE": {"phonetic": "/feɪ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A Hebrew letter (pe)."]}]},
    "GI": {"phonetic": "/ɡiː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A martial arts uniform."]}]},
    "GO": {"phonetic": "/ɡoʊ/", "meanings": [{"partOfSpeech": "verb", "definitions": ["Move from one place to another; travel."]}]},
    "HA": {"phonetic": "/hɑː/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Expressing triumph, surprise, or laughter."]}]},
    "HE": {"phonetic": "/hiː/", "meanings": [{"partOfSpeech": "pronoun", "definitions": ["Used to refer to a person or animal of the male sex."]}]},
    "HI": {"phonetic": "/haɪ/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Used as a friendly greeting or to attract attention."]}]},
    "HM": {"phonetic": "/hmː/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Expressing consideration or hesitation."]}]},
    "HO": {"phonetic": "/hoʊ/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Used to call attention or express surprise or delight."]}]},
    "ID": {"phonetic": "/ɪd/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The part of the psyche associated with instinctual impulses and primitive desires."]}]},
    "IF": {"phonetic": "/ɪf/", "meanings": [{"partOfSpeech": "conjunction", "definitions": ["Introducing a conditional clause."]}]},
    "IN": {"phonetic": "/ɪn/", "meanings": [{"partOfSpeech": "preposition", "definitions": ["Expressing the situation of something that is enclosed or surrounded by something else."]}]},
    "IS": {"phonetic": "/ɪz/", "meanings": [{"partOfSpeech": "verb", "definitions": ["Third-person singular present indicative of be."]}]},
    "IT": {"phonetic": "/ɪt/", "meanings": [{"partOfSpeech": "pronoun", "definitions": ["Used to refer to a thing previously mentioned or easily identified."]}]},
    "JO": {"phonetic": "/dʒoʊ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A sweetheart or darling (Scottish)."]}]},
    "KA": {"phonetic": "/kɑː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["In ancient Egyptian religion, the spiritual double or vital spark of a human."]}]},
    "KI": {"phonetic": "/kiː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["Qi or vital life force in Japanese martial arts."]}]},
    "LA": {"phonetic": "/lɑː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The sixth musical solfège syllable."]}]},
    "LAH": {"phonetic": "/lɑː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A syllable used in solfège to represent the sixth note of a musical major scale (variant of la); an exclamation used in informal speech."]}]},
    "LI": {"phonetic": "/liː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A traditional Chinese unit of distance equal to about 500 meters."]}]},
    "LO": {"phonetic": "/loʊ/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Used to draw attention to an interesting or unexpected event."]}]},
    "MA": {"phonetic": "/mɑː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["Informal term for mother."]}]},
    "ME": {"phonetic": "/miː/", "meanings": [{"partOfSpeech": "pronoun", "definitions": ["Used by a speaker to refer to himself or herself as the object of a verb or preposition."]}]},
    "MI": {"phonetic": "/miː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The third note of a musical scale in solfège."]}]},
    "MM": {"phonetic": "/mː/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Expressing satisfaction, agreement, or delight."]}]},
    "MO": {"phonetic": "/moʊ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A moment or short period of time."]}]},
    "MU": {"phonetic": "/mjuː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The twelfth letter of the Greek alphabet (Μ, μ)."]}]},
    "MY": {"phonetic": "/maɪ/", "meanings": [{"partOfSpeech": "determiner", "definitions": ["Belonging to or associated with the speaker."]}]},
    "NA": {"phonetic": "/nɑː/", "meanings": [{"partOfSpeech": "adverb", "definitions": ["No or not (Scottish/dialect)."]}]},
    "NE": {"phonetic": "/niː/", "meanings": [{"partOfSpeech": "conjunction", "definitions": ["Nor; not (archaic)."]}]},
    "NO": {"phonetic": "/noʊ/", "meanings": [{"partOfSpeech": "determiner", "definitions": ["Not any; indicating a negative response or refusal."]}]},
    "NU": {"phonetic": "/njuː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The thirteenth letter of the Greek alphabet (Ν, ν)."]}]},
    "OD": {"phonetic": "/ɒd/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A hypothetical force once thought to pervade nature."]}]},
    "OE": {"phonetic": "/oʊ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A small island or grandchild (dialect)."]}]},
    "OF": {"phonetic": "/ɒv/", "meanings": [{"partOfSpeech": "preposition", "definitions": ["Expressing the relationship between a part and a whole."]}]},
    "OH": {"phonetic": "/oʊ/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Used to express a range of emotions such as surprise, anger, or disappointment."]}]},
    "OI": {"phonetic": "/ɔɪ/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Used to attract someone's attention or express indignation."]}]},
    "OK": {"phonetic": "/oʊˈkeɪ/", "meanings": [{"partOfSpeech": "adjective", "definitions": ["Satisfactory; acceptable; in good order."]}]},
    "OM": {"phonetic": "/oʊm/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A sacred sound and a spiritual symbol in Hinduism and Buddhism."]}]},
    "ON": {"phonetic": "/ɒn/", "meanings": [{"partOfSpeech": "preposition", "definitions": ["Physically in contact with and supported by a surface."]}]},
    "OP": {"phonetic": "/ɒp/", "meanings": [{"partOfSpeech": "noun", "definitions": ["An operation or photo opportunity."]}]},
    "OR": {"phonetic": "/ɔːr/", "meanings": [{"partOfSpeech": "conjunction", "definitions": ["Used to link alternatives."]}]},
    "OS": {"phonetic": "/ɒs/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A bone; or an orifice or mouth."]}]},
    "OW": {"phonetic": "/aʊ/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Used to express sudden pain."]}]},
    "OX": {"phonetic": "/ɒks/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A domesticated bovine animal kept for milk or meat; a bullock."]}]},
    "OY": {"phonetic": "/ɔɪ/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Used to express dismay, pain, or grief (Yiddish)."]}]},
    "PA": {"phonetic": "/pɑː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["Informal term for father; or a Māori fortified village."]}]},
    "PE": {"phonetic": "/peɪ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The seventeenth letter of the Hebrew alphabet."]}]},
    "PI": {"phonetic": "/paɪ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The sixteenth letter of the Greek alphabet (Π, π), representing the ratio of a circle's circumference to its diameter (~3.14159)."]}]},
    "PO": {"phonetic": "/poʊ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A chamber pot (informal)."]}]},
    "QI": {"phonetic": "/tʃiː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The circulating life force whose flow is believed to be vital for health in Chinese philosophy."]}]},
    "RE": {"phonetic": "/reɪ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The second tone of a diatonic scale in solfège; or with reference to."]}]},
    "SH": {"phonetic": "/ʃː/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Used to urge silence."]}]},
    "SI": {"phonetic": "/siː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The seventh tone of the musical scale in solfège (ti)."]}]},
    "SO": {"phonetic": "/soʊ/", "meanings": [{"partOfSpeech": "adverb", "definitions": ["To such a great degree; therefore."]}]},
    "TA": {"phonetic": "/tɑː/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Thank you (informal British)."]}]},
    "TE": {"phonetic": "/tiː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The seventh tone of the scale in solfège (variant of ti)."]}]},
    "TI": {"phonetic": "/tiː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The seventh tone of the diatonic scale in solfège."]}]},
    "TO": {"phonetic": "/tuː/", "meanings": [{"partOfSpeech": "preposition", "definitions": ["Expressing motion in the direction of a particular location."]}]},
    "UH": {"phonetic": "/ʌ/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Expressing hesitation, doubt, or a pause."]}]},
    "UM": {"phonetic": "/ʌm/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["Used to indicate hesitation or doubt in speech."]}]},
    "UN": {"phonetic": "/ʌn/", "meanings": [{"partOfSpeech": "pronoun", "definitions": ["One (dialect)."]}]},
    "UP": {"phonetic": "/ʌp/", "meanings": [{"partOfSpeech": "adverb", "definitions": ["Towards a higher place or position."]}]},
    "US": {"phonetic": "/ʌs/", "meanings": [{"partOfSpeech": "pronoun", "definitions": ["Used by a speaker to refer to themselves and one or more other people as the object of a verb or preposition."]}]},
    "UT": {"phonetic": "/ʊt/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The syllable once used for the first note of the diatonic scale."]}]},
    "WE": {"phonetic": "/wiː/", "meanings": [{"partOfSpeech": "pronoun", "definitions": ["Used by a speaker to refer to themselves and one or more other people considered together."]}]},
    "WO": {"phonetic": "/woʊ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["Woe (archaic)."]}]},
    "XI": {"phonetic": "/zaɪ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The fourteenth letter of the Greek alphabet (Ξ, ξ)."]}]},
    "XU": {"phonetic": "/suː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A monetary unit of Vietnam, equal to one hundredth of a dong."]}]},
    "YA": {"phonetic": "/jɑː/", "meanings": [{"partOfSpeech": "pronoun", "definitions": ["Informal spelling of you."]}]},
    "YE": {"phonetic": "/jiː/", "meanings": [{"partOfSpeech": "pronoun", "definitions": ["Archaic plural form of you."]}]},
    "YO": {"phonetic": "/joʊ/", "meanings": [{"partOfSpeech": "interjection", "definitions": ["An informal greeting or attention-getter."]}]},
    "ZA": {"phonetic": "/zɑː/", "meanings": [{"partOfSpeech": "noun", "definitions": ["Slang for pizza."]}]},

    # Common Crossword/Core English words
    "CAT": {"phonetic": "/kæt/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A small domesticated carnivorous mammal with soft fur and retractable claws."]}]},
    "DOG": {"phonetic": "/dɔːɡ/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A domesticated carnivorous mammal having a barking or howling voice."]}]},
    "PLAY": {"phonetic": "/pleɪ/", "meanings": [{"partOfSpeech": "verb", "definitions": ["Engage in activity for enjoyment and recreation rather than a serious or practical purpose."]}]},
    "GAME": {"phonetic": "/ɡeɪm/", "meanings": [{"partOfSpeech": "noun", "definitions": ["An activity that one engages in for amusement, fun, or competition."]}]},
    "WORD": {"phonetic": "/wɜːrd/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A single distinct meaningful element of speech or writing."]}]},
    "CROSS": {"phonetic": "/krɔːs/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A mark, object, or figure formed by two intersecting lines or pieces."]}]},
    "TILE": {"phonetic": "/taɪl/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A thin rectangular slab of baked clay or flat piece used in games."]}]},
    "STAR": {"phonetic": "/stɑːr/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A fixed luminous point in the night sky which is a large, remote incandescent body."]}]},
    "MOON": {"phonetic": "/muːn/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The natural satellite of the earth, visible by reflected sunlight."]}]},
    "SUN": {"phonetic": "/sʌn/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The star around which the earth orbits and from which it receives light and warmth."]}]},
    "FIRE": {"phonetic": "/faɪər/", "meanings": [{"partOfSpeech": "noun", "definitions": ["Combustion or burning, in which substances combine chemically with oxygen producing heat and light."]}]},
    "WATER": {"phonetic": "/ˈwɔːtər/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A colorless, transparent, odorless liquid that forms the seas, lakes, rivers, and rain."]}]},
    "BOARD": {"phonetic": "/bɔːrd/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A long, thin, flat piece of wood or other hard material, or the surface on which a game is played."]}]},
    "SCORE": {"phonetic": "/skɔːr/", "meanings": [{"partOfSpeech": "noun", "definitions": ["The number of points, goals, or runs achieved in a game or match."]}]},
    "RACK": {"phonetic": "/ræk/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A framework, typically with rails or bars, for holding or storing things like tiles."]}]},
    "CARD": {"phonetic": "/kɑːrd/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A piece of thick, stiff paper or plastic used for playing games or providing special powers."]}]},
    "SPELL": {"phonetic": "/spɛl/", "meanings": [{"partOfSpeech": "verb", "definitions": ["Write or name the letters that form a word in correct order."]}]},
    "LETTER": {"phonetic": "/ˈlɛtər/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A character representing one or more of the sounds used in speech; any of the symbols of an alphabet."]}]},
    "SHIELD": {"phonetic": "/ʃiːld/", "meanings": [{"partOfSpeech": "noun", "definitions": ["A broad piece of metal or protective armor used to defend against attack or damage."]}]},
    "FREEZE": {"phonetic": "/friːz/", "meanings": [{"partOfSpeech": "verb", "definitions": ["Be turned into ice or another solid as a result of extreme cold; immobilize."]}]},
    "DOUBLE": {"phonetic": "/ˈdʌb.əl/", "meanings": [{"partOfSpeech": "adjective", "definitions": ["Consisting of two equal, identical, or similar parts or things."]}]},
    "TRIPLE": {"phonetic": "/ˈtrɪp.əl/", "meanings": [{"partOfSpeech": "adjective", "definitions": ["Consisting of three parts, things, or elements."]}]},
}
